import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'

const geist = Geist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
      <body className={`$[geist.className} overflow-hidden`}>
         <header className="flex justify-between items-center p-4 gap-4 h-16">
            <div className="font-bold italic text-3xl">bolt</div>
            <div className="flex gap-4">
              <SignedOut>
              <SignInButton />
              <SignUpButton>
                <button className="bg-cyan-600 text-white rounded-full font-medium text-sm sm:text-base h-12 sm:h-12 px-4 sm:px-5 cursor-pointer">
                  Sign Up
                </button>
              </SignUpButton>
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
            </div>
            
          </header>
        {children}
        </body>
    </html>
    </ClerkProvider>
  );
}
